
server:
  port: 2000
spring:
  application:
    name: zuul-server
zuul:
  ignoredServices: '*'
  routes:
    plat:
      path: /plan/** #平台服务的请求路径
      serviceId: plan-service
    product:
      path: /product/** #平台服务的请求路径
      serviceId: product-service
  prefix: /services #请求前缀
